export const COLOMBIA_LOCATIONS: Record<string, string[]> = {
  "Amazonas": ["Leticia", "Puerto Nariño"],
  "Antioquia": ["Medellín", "Bello", "Envigado", "Itagüí", "Rionegro", "Sabaneta"],
  "Arauca": ["Arauca", "Arauquita"],
  "Atlántico": ["Barranquilla", "Soledad", "Malambo", "Sabanalarga"],
  "Bogotá D.C.": ["Bogotá"],
  "Bolívar": ["Cartagena", "Magangué", "Turbaco"],
  "Boyacá": ["Tunja", "Duitama", "Sogamoso"],
  "Caldas": ["Manizales", "La Dorada", "Chinchiná"],
  "Caquetá": ["Florencia", "San Vicente del Caguán"],
  "Casanare": ["Yopal", "Aguazul"],
  "Cauca": ["Popayán", "Santander de Quilichao"],
  "Cesar": ["Valledupar", "Aguachica"],
  "Chocó": ["Quibdó", "Istmina"],
  "Córdoba": ["Montería", "Lorica"],
  "Cundinamarca": ["Soacha", "Zipaquirá", "Facatativá", "Chía", "Mosquera"],
  "Guainía": ["Inírida"],
  "Guaviare": ["San José del Guaviare"],
  "Huila": ["Neiva", "Pitalito"],
  "La Guajira": ["Riohacha", "Maicao"],
  "Magdalena": ["Santa Marta", "Ciénaga"],
  "Meta": ["Villavicencio", "Acacías"],
  "Nariño": ["Pasto", "Tumaco", "Ipiales"],
  "Norte de Santander": ["Cúcuta", "Ocaña", "Villa del Rosario"],
  "Putumayo": ["Mocoa", "Puerto Asís"],
  "Quindío": ["Armenia", "Calarcá"],
  "Risaralda": ["Pereira", "Dosquebradas"],
  "San Andrés y Providencia": ["San Andrés"],
  "Santander": ["Bucaramanga", "Floridablanca", "Barrancabermeja", "Girón"],
  "Sucre": ["Sincelejo", "Corozal"],
  "Tolima": ["Ibagué", "Espinal"],
  "Valle del Cauca": ["Cali", "Buenaventura", "Palmira", "Tuluá"],
  "Vaupés": ["Mitú"],
  "Vichada": ["Puerto Carreño"]
};